[package]
name = "cspx-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
hex.workspace = true
rayon.workspace = true
serde.workspace = true

[dev-dependencies]
tempfile = "3.10"
